# Generated by Django 3.2.24 on 2024-02-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='study_date',
            field=models.DateField(null=True, verbose_name='勉強日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.IntegerField(null=True, verbose_name='勉強終了時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='item',
            field=models.CharField(blank=True, max_length=200, verbose_name='勉強項目'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.IntegerField(null=True, verbose_name='勉強開始時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_length',
            field=models.IntegerField(null=True, verbose_name='勉強時間の長さ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
